package com.robinsmorton.rmappandroid.model

import com.google.gson.annotations.SerializedName

data class Fields(
    @SerializedName("@odata.etag")
    val etag: String? = null,
    val Attachments: Boolean? = null,
    val AuthorLookupId: String? = null,
    val ContentType: String? = null,
    val Created: String? = null,
    val Edit: String? = null,
    val EditorLookupId: String? = null,
    val Estimate_x0020_Number: String? = null,
    val FolderChildCount: String? = null,
    val IsActive: Boolean? = null,
    val ItemChildCount: String? = null,
    val LinkTitle: String? = null,
    val LinkTitleNoMenu: String? = null,
    val Modified: String? = null,
    val Title: String? = null,
    val _ComplianceFlags: String? = null,
    val _ComplianceTag: String? = null,
    val _ComplianceTagUserId: String? = null,
    val _ComplianceTagWrittenTime: String? = null,
    val _UIVersionString: String? = null,
    val buttonimage: String? = null,
    val id: String? = null,
    val AppOrder: Int? = null,
    val AppImage: String? = null,
    val AppLink: AppLink? = null,
    val AppLink_Mac: AppLinkMac? = null,
    val field_1: String? = null,
    val AppEditorLookupId: String? = null,
    val Architect: String? = null,
    val City: String? = null,
    val County: String? = null,
    val Date: String? = null,
    val FedStatePriv: String? = null,
    val Green_x0020_Practices_x0020_and_: String? = null,
    val LEED_x0020_Project: String? = null,
    val Lead_x0020_Estimator: String? = null,
    val Operations_x0020_Manager: String? = null,
    val Owner: String? = null,
    val Request_x0020_Year: String? = null,
    val Requested_x0020_By: String? = null,
    val Scope: String? = null,
    val State: String? = null,
    val Status: String? = null,
    val UnionReq: String? = null
)