package com.example.rmapplication.model.jobrequest

import com.google.gson.annotations.SerializedName


data class Fields(
    @SerializedName("@odata.etag")
    val  etag: String,
    val AAndE: String,
    val AppEditorLookupId: String,
    val Approve: String,
    val Architect_x0020_Phone_x0020_Numb: String,
    val Architect_x0020__x0020_Contact: String,
    val Architectural_x0020_Firm: String,
    val Attachments: Boolean,
    val AuthorLookupId: String,
    val City: String,
    val Completion_x0020_Date: String,
    val Construction_x0020_Cost: Int,
    val ContentType: String,
    val Created: String,
    val CurrentUser: String,
    val Edit: String,
    val EditorLookupId: String,
    val Estimate_x0020_Number: String,
    val Estimate_x0020_Transfer: Boolean,
    val Estimate_x0020_Transfer_x0020_to: Boolean,
    val Estimator: String,
    val FolderChildCount: String,
    val ItemChildCount: String,
    val JobRequiresCertifiedPayroll: String,
    val Job_x0020_Number: String,
    val LinkTitle: String,
    val LinkTitleNoMenu: String,
    val Modified: String,
    val New_x0020_SF: Int,
    val Notes: String,
    val Operations_x0020_Manager: String,
    val Owner: String,
    val OwnerProvided: String,
    val Owner_x0020_Contact: String,
    val Owner_x0020_Phone_x0020_Number: String,
    val Renovated_x0020_SF: Int,
    val RequestYear: String,
    val Requested_x0020_By: String,
    val Scope: String,
    val Secretary: String,
    val SmallTools: String,
    val Sr_x002e__x0020_Project_x0020_Ma: String,
    val Start_x0020_Date: String,
    val State: String,
    val SubguardAllowed: String,
    val Superintendent: String,
    val Title: String,
    val Transfer_x0020__x002d__x0020_Off: String,
    val Type_x0020_of_x0020_Structure: String,
    val UnitLaborRates: String,
    val ZipCode: String,
    val _ComplianceFlags: String,
    val _ComplianceTag: String,
    val _ComplianceTagUserId: String,
    val _ComplianceTagWrittenTime: String,
    val _UIVersionString: String,
    val _x0023__x0020_of_x0020_Beds: String,
    val _x0023__x0020_of_x0020_Floors: String,
    val id: String
)